POST http://localhost:8080/coffee
Content-Type: application/json

{
  "coffeeType": "sdlkflsdkflsdklfksdlfkksdlf",
  "smell": "sdlkflsdkflsdklfksdlfkksdlf",
  "favor": "sdlkflsdkflsdklfksdlfkksdlf",
  "origin": "sdlkflsdkflsdklfksdlfkksdlf",
  "shots": "sdlkflsdkflsdklfksdlfkksdlf",
  "isLatte": false
}
########
