POST https://blog-kg6mm24jeq-du.a.run.app/client
Content-Type: application/json

{


   "name": "고경준 천재님이십니3333333333",
   "nickname": "sdflkgsdflkgdfkg",
   "age": "sdflkgsdflkgdfkg",
   "sex": "sdflkgsdflkgdfkg",
   "college": "sdflkgsdflkgdfkg",
   "location": "sdflkgsdflkgdfkg"


}
######## https://kotlin-demo002-kg6mm24jeq-du.a.run.app

PATCH http://localhost:4000/client/64b75892ccdaf961c92cc86e
Content-Type: application/json

{

"name": "kyungjoon ige 고경준 천재님이십니다sdlkflsdkflkd====>>>>>>",
"nickname": "sdflkgsdflkgdfkg",
"age": "sdflkgsdflkgdfkg",
"sex": "sdflkgsdflkgdfkg",
"college": "sdflkgsdflkgdfkg",
"location": "sdflkgsdflkgdfkg"


}
