POST http://localhost:8080/login
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmcmVzaCIsImlhdCI6MTY4NDkyMjIwOCwiZXhwIjoxNjg0OTI0MDA4LCJpZCI6IuyVhOydtOuUlCIsImVtYWlsIjoiYWp1ZnJlc2hAZ21haWwuY29tIn0.gXj3yLtyAWxgVg0uUm-p4NM_Ya_kAbFlY46ir6PGk8Y

{
  "id": "lance777",
  "pwd": "1114"

}
